=== metno/eps2probandltf/etc/eps2probandltf.parameters.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="cfnamed_type">
		<xs:attribute name="cfname" type="xs:string" use="required" />
	</xs:complexType>

	<xs:simpleType name="DataType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="double" />
			<xs:enumeration value="float" />
			<xs:enumeration value="int" />
			<xs:enumeration value="short" />
			<xs:enumeration value="char" />
			<xs:enumeration value="String" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="cfnamed_value_type">
		<xs:complexContent>
			<xs:extension base="cfnamed_type">
				<xs:attribute name="value" />
				<xs:attribute name="unit" type="DataType" default="String" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="value_type">
		<xs:attribute name="value" type="xs:float" use="required" />
	</xs:complexType>
	
	<xs:complexType name="complete_dimension_type">
		<xs:complexContent>
			<xs:extension base="cfnamed_type">
				<xs:sequence>
					<xs:element name="attribute" type="cfnamed_value_type"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="value" type="value_type"
						minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>	
	</xs:complexType>

	<xs:complexType name="parameter_type">
		<xs:complexContent>
			<xs:extension base="cfnamed_type">
				<xs:attribute name="time_offset" type="xs:int" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="complete_parameter_type">
		<xs:complexContent>
			<xs:extension base="parameter_type">
				<xs:sequence>
					<xs:element name="attribute" type="cfnamed_value_type"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="dimension" type="cfnamed_value_type"
						minOccurs="0" maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="variable_type">
		<xs:complexContent>
			<xs:extension base="cfnamed_type">
				<xs:sequence>
					<xs:element name="dimension" type="cfnamed_type" 
						minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="attribute" type="cfnamed_value_type"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="value" type="value_type"
						minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="pgen_probabilty_parameter_type">
		<xs:sequence>
			<xs:element name="cloud_cover" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_from_in" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_to_in" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="air_pressure" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="dew_point_temperature" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="sea_surface_wave_significant_height" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="yr_symbol" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="probability_yr_symbol" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature_10" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature_25" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature_50" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature_75" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature_90" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature_1_prob" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="temperature_2_prob" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="x_wind" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="y_wind" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="wind_prob" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="wind_10" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="wind_25" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="wind_50" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="wind_75" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="wind_90" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_out" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_10" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_25" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_50" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_75" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_90" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_1" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_2" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_3" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_4" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_5" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="precipitation_6" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="cloud_10" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="cloud_25" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="cloud_50" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="cloud_75" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="cloud_90" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="significant_wave_height_10" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="significant_wave_height_25" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="significant_wave_height_50" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="significant_wave_height_75" type="complete_parameter_type" minOccurs="0" />
			<xs:element name="significant_wave_height_90" type="complete_parameter_type" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="pgen_probabilty_type">
		<xs:sequence>
			<xs:element name="global_attribute" type="cfnamed_value_type"  minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="direct_transfer" type="cfnamed_type" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="dimension" type="complete_dimension_type" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="variable" type="variable_type" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="parameter" type="pgen_probabilty_parameter_type" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="eps2probandltf" type="pgen_probabilty_type" />

</xs:schema>

=== metno/eps2probandltf/etc/eps2probandltf-1.1.parameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eps2probandltf_config>

<eps2probandltf xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="eps2probandltf.parameters.xsd">

	<global_attribute cfname="Conventions" value="CF-1.0 met.no-extensions"/>
	<global_attribute cfname="title" value="met.no probability forecasts"/>
	<global_attribute cfname="summary" value="Selected weather parameters with probabilities, based on ensemble data"/>
	<global_attribute cfname="keywords" value="ensemble, confidence, percentile, yr.no"/>
	<global_attribute cfname="id" value="probability_forecast"/>
	<global_attribute cfname="naming_authority" value="no.met"/>
	<global_attribute cfname="cdm_data_type" value="Grid"/>
	<global_attribute cfname="institution" value="met.no"/>

	<direct_transfer cfname="forecast_reference_time" />
	<direct_transfer cfname="runtime" />
	<direct_transfer cfname="altitude" />
	<direct_transfer cfname="time" />
	<direct_transfer cfname="longitude" />
	<direct_transfer cfname="latitude" />
	<direct_transfer cfname="x" />
	<direct_transfer cfname="y" />
	
	<dimension cfname="percentile">
		<attribute cfname="units" value="1" />
		<attribute cfname="metno_name" value="cumulative_distribution_function_over_realization" />
		<attribute cfname="long_name" value="cumulative_distribution_function_over_realization" />
		<value value="0.1" />
		<value value="0.25" />
		<value value="0.5" />
		<value value="0.75" />
		<value value="0.9" />
	</dimension>
	<dimension cfname="interval_of_air_temperature">
		<attribute cfname="bounds" value="temperature_bounds" />
		<attribute cfname="units" value="K" />
 		<attribute cfname="standard_name" value="air_temperature" />
		<attribute cfname="long_name" value="air_temperature offset from a given value (in either direction)" />
		<value value="1.5" />
		<value value="2.5" />
	</dimension>
	<dimension cfname="confidence_bounds">
		<value value="0" />
		<value value="1" />
	</dimension>
	
	<dimension cfname="precipitation_limit">
		<attribute cfname="units" value="kg/m2" />
		<attribute cfname="metno_name" value="limit_of_precipitation_amount" />
		<attribute cfname="long_name" value="limit_of_precipitation_amount" />
		<value value=".1" />
		<value value=".2" />
		<value value=".5" />
		<value value="1" />
		<value value="2" />
		<value value="5" />
	</dimension>
	
	<variable cfname="temperature_bounds">
		<dimension cfname="confidence_bounds" />
		<dimension cfname="interval_of_air_temperature" />
		<attribute cfname="long_name" value="bounds of temperature - for confidence variables" />
		<value value="-1.5" />
		<value value="1.5" />
		<value value="-2.5" />
		<value value="2.5" />
	</variable>
	
	<parameter>

		<cloud_cover cfname="cloud_area_fraction">
			<attribute cfname="standard_name" value="cloud_area_fraction" />
			<attribute cfname="long_name" value="cloud_area_fraction" />
			<attribute cfname="units" value="1" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</cloud_cover>		

		<precipitation_from_in cfname="precipitation_amount_acc" />

		<precipitation_to_in cfname="precipitation_amount_acc"
			time_offset="6" />

		<temperature cfname="air_temperature_2m">
			<attribute cfname="units" value="K" />
			<attribute cfname="standard_name" value="air_temperature" />
			<attribute cfname="long_name" value="air_temperature_2m" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
			<attribute cfname="ancillary_variables" value="air_temperature_confidence" />
		</temperature>

		<temperature_min cfname="air_temperature_2m_min6h">
			<attribute cfname="units" value="K" />
			<attribute cfname="standard_name" value="air_temperature" />
			<attribute cfname="long_name" value="air_temperature minimum over a time period" />
			<attribute cfname="cell_methods" value="time: minimum (interval: 6 hours)" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</temperature_min>

		<temperature_max cfname="air_temperature_2m_max6h">
			<attribute cfname="units" value="K" />
			<attribute cfname="standard_name" value="air_temperature" />
			<attribute cfname="long_name" value="air_temperature maximum over a time period" />
			<attribute cfname="cell_methods" value="time: maximum (interval: 6 hours)" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</temperature_max>

		<relative_humidity cfname="relative_humidity_2m">
			<attribute cfname="units" value="1" />
			<attribute cfname="standard_name" value="relative_humidity" />
			<attribute cfname="long_name" value="relative_humidity_2m" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</relative_humidity>

		<air_pressure cfname="sea_level_pressure">
			<attribute cfname="units" value="Pa" />
			<!-- <attribute cfname="scale_factor" value="10" unit="float"/> -->
			<attribute cfname="standard_name" value="air_pressure_at_sea_level" />
			<attribute cfname="long_name" value="air_pressure_at_sea_level" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</air_pressure>

		<dew_point_temperature cfname="dew_point_temperature" />

		<sea_surface_wave_significant_height cfname="significant_wave_height" />
 
		<yr_symbol cfname="weather_symbol" time_offset="6">
			<attribute cfname="metno_name" value="weather_symbol status_flag" />
			<attribute cfname="long_name" value="weather_symbol status_flag" />
			<attribute cfname="flag_values" value="0, 1, 2, 3, 4, 5, 9, 10, 40, 41, 46"/>
			<attribute cfname="flag_meanings" value="error sun light_cloud partly_cloud cloud light_rain_sun rain heavy_rain drizzle_sun rain_sun drizzle"/>
			<attribute cfname="ancillary_variables" value="weather_symbol_confidence" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</yr_symbol>
		
		<probability_yr_symbol cfname="weather_symbol_confidence"
			time_offset="6">
			<attribute cfname="units" value="%" />
			<attribute cfname="metno_name" value="weather_symbol confidence" />
			<attribute cfname="long_name" value="weather_symbol confidence" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</probability_yr_symbol>

		<temperature_10 cfname="air_temperature_percentiles">
			<attribute cfname="units" value="K" />
			<attribute cfname="standard_name" value="air_temperature" />
			<attribute cfname="long_name" value="air_temperature" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
			<dimension cfname="percentile" value="0.1" />
		</temperature_10>
		<temperature_25 cfname="air_temperature_percentiles">
			<dimension cfname="percentile" value="0.25" />
		</temperature_25>
		<temperature_50 cfname="air_temperature_percentiles">
			<dimension cfname="percentile" value="0.5" />
		</temperature_50>
		<temperature_75 cfname="air_temperature_percentiles">
			<dimension cfname="percentile" value="0.75" />
		</temperature_75>
		<temperature_90 cfname="air_temperature_percentiles">
			<dimension cfname="percentile" value="0.9" />
		</temperature_90>

		<temperature_1_prob cfname="air_temperature_confidence">
			<attribute cfname="units" value="%" />
			<attribute cfname="metno_name" value="air_temperature confidence" />
			<attribute cfname="long_name"
				value="probabilty of air_temperature within +/- interval_of_air_temperature" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
			<dimension cfname="interval_of_air_temperature" value="1.5" />
		</temperature_1_prob>
		<temperature_2_prob cfname="air_temperature_confidence">
			<dimension cfname="interval_of_air_temperature" value="2.5" />
		</temperature_2_prob>

		<x_wind cfname="x_wind_10m">
			<attribute cfname="units" value="m/s" />
			<attribute cfname="standard_name" value="x_wind" />
			<attribute cfname="long_name" value="x_wind" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
			<attribute cfname="ancillary_variables" value="wind_speed_confidence" />
		</x_wind>
		<y_wind cfname="y_wind_10m">
			<attribute cfname="units" value="m/s" />
			<attribute cfname="standard_name" value="y_wind" />
			<attribute cfname="long_name" value="y_wind" />
			<attribute cfname="ancillary_variables" value="wind_speed_confidence" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</y_wind>
		<wind_prob cfname="wind_speed_confidence">
			<attribute cfname="units" value="%" />
			<attribute cfname="metno_name" value="wind_speed confidence" />
			<attribute cfname="long_name" value="wind_speed confidence" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</wind_prob>
		<wind_10 cfname="wind_speed">
			<attribute cfname="units" value="m/s" />
			<attribute cfname="standard_name" value="wind_speed" />
			<attribute cfname="long_name" value="wind_speed" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
			<dimension cfname="percentile" value="0.1" />
		</wind_10>
		<wind_25 cfname="wind_speed">
			<dimension cfname="percentile" value="0.25" />
		</wind_25>
		<wind_50 cfname="wind_speed">
			<dimension cfname="percentile" value="0.5" />
		</wind_50>
		<wind_75 cfname="wind_speed">
			<dimension cfname="percentile" value="0.75" />
		</wind_75>
		<wind_90 cfname="wind_speed">
			<dimension cfname="percentile" value="0.9" />
		</wind_90>

		<precipitation_out cfname="precipitation_amount"
			time_offset="6">
			<attribute cfname="units" value="kg/m2" />
			<attribute cfname="standard_name" value="precipitation_amount" />
			<attribute cfname="long_name" value="precipitation_amount" />
			<attribute cfname="cell_methods" value="time: sum" />
			<attribute cfname="ancillary_variables" value="precipitation_limit_confidence" />
			<attribute cfname="_FillValue" value="-32767" unit="float"/>
		</precipitation_out>

		<precipitation_10 cfname="precipitation_percentiles"
			time_offset="6">
			<attribute cfname="units" value="kg/m2" />
			<attribute cfname="standard_name" value="precipitation_amount" />
